---
- name: pull mini_project image
  hosts: all
  tasks:
          - name: Pull junit devops image 
            docker_image:
                  name: adityakaka/calci
                  source: pull

          - name: pull the image
            docker_image:
                name: adityakaka/calci
                source: pull

          - name: creating updated container
            shell: docker run -id adityakaka/calci
