---
- name: pull mini_project image
  hosts: all
  tasks:

          - name: pull the image
            servive:
              name: docker
              source: started


          - name: pull the image
            docker_image:
                name: adityakaka/calci
                source: pull

          - name: creating updated container
            shell: docker run -id adityakaka/calci
