---
- name: pull mini_project image
  hosts: all
  tasks:
          - name: Pull junit devops image 
            docker_image:
                  name: aditya-k-7/SPE_Mini_Project
                  source: pull

          - name: pull the image
            docker_image:
                name: aditya-k-7/SPE_Mini_Project
                source: pull

          - name: creating updated container
            shell: docker run -id aditya-k-7/SPE_Mini_Project
